spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
server:
  port: 8001
eureka:
  instance:
    hostname: eureka8001.com
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka8002.com:8002/eureka/,http://eureka8003.com:8003/eureka/
---
spring:
  profiles: test
server:
  port: 8002
eureka:
  instance:
    hostname: eureka8001.com
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka8002.com:8002/eureka/,http://eureka8003.com:8003/eureka/
